### ISSUE TITLE
Exception in thread "ForkJoinPool-1-worker-2" java.lang.StackOverflowError 

### ISSUE THREAD

**Issue by Yyukan** [kamon-io/kamon-cassandra#4]
I try to use Kamon to monitor Cassandra queries with the following versions:

jdk:10
cassandra-driver-core: 3.6.0
kamon-cassandra-client:1.0.5
kanela-agent:0.0.15

Application starts fine and provides metrics like "cassandra_query_duration_seconds_bucket", but when I  execute Cassandra query I get an exception:
`Exception in thread "ForkJoinPool-1-worker-2" java.lang.StackOverflowError
	at com.datastax.driver.core.AbstractSession.prepareAsync(AbstractSession.java:111)
	at kamon.cassandra.client.KamonSession.prepareAsync(KamonSession.scala:51)
	at com.datastax.driver.core.AbstractSession.prepareAsync(AbstractSession.java:116)
	at kamon.cassandra.client.KamonSession.prepareAsync(KamonSession.scala:51)
	at com.datastax.driver.core.AbstractSession.prepareAsync(AbstractSession.java:116)
	at kamon.cassandra.client.KamonSession.prepareAsync(KamonSession.scala:51)
	at com.datastax.driver.core.AbstractSession.prepareAsync(AbstractSession.java:116)
	at kamon.cassandra.client.KamonSession.prepareAsync(KamonSession.scala:51)
	at com.datastax.driver.core.AbstractSession.prepareAsync(AbstractSession.java:116)
         ...
`
Without specifying Kanela as the javaagent it works fine.

**Comment by damdev** [comment]
Hi @Yyukan could you try with this snapshot version?

https://bintray.com/kamon-io/snapshots/kamon-cassandra/1.0.5-9aaea1fdd8bddae5dbc33d24884fcd94dfe7bcae ?

**Comment by Yyukan** [comment]
hey @damdev, thank you for the update. So far so good, simple query SELECT now() FROM system.local; works fine and I have following metrics: 

- cassandra_query_count_total
- cassandra_client_inflight_driver_bucket
- cassandra_trashed_connections_bucket
- cassandra_connection_pool_size_bucket
- cassandra_query_duration_seconds_bucket
- cassandra_client_inflight_bucket

Let me a few days for testing...  

When do you plan to release a new version ?

**Comment by damdev** [comment]
@Yyukan once you give us an ok, or even better give us a minimal example of this issue (i can't reproduce it) to add to the tests suite. We can release a new version with the fix. Thanks for the feedback!

**Comment by Yyukan** [comment]
Yep, I have no exceptions in my logs anymore, thanks a lot!

**Comment by dpsoft** [comment]
@Yyukan I've just released https://bintray.com/kamon-io/releases/kamon-cassandra/1.0.6 with this changes.
